language: csharp
dist: trusty
sudo: required 
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet test ./ContinuousIntegrationHelloWorld.Tests/ContinuousIntegrationHelloWorld.Tests.csproj -c Release -f netcoreapp2.0